name: Deploy Static Site
on:
  push:
    branches: master
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:12
    steps:
      - uses: actions/checkout@v1
      - name: deploy static site
        run: |
          apt-get update
          apt-get install -y git
          git config --global user.email "deploy@localhost"
          git config --global user.name "Github Actions"
          yarn
          yarn deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
