name: Deploy Static Site
on:
  push:
    branches: master
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:12-alpine
    steps:
      - uses: actions/checkout@v1
      - name: deploy static site
        run: |
          apk add --update git
          yarn
          yarn deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
